/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "My_Platform_Types.h"

#define RCC_BASE (0x40021000)
#define GPIO_PA  (0x40010800)
#define RCC_APB2ENR *(vuint32_t *)(RCC_BASE+0x18)
#define GPIO_PA_CRH *(vuint32_t *)(GPIO_PA+0x04)
#define GPIO_PA_ODR *(vuint32_t *)(GPIO_PA+0x0c)

typedef union
{
	vuint32_t All_Ports;
	struct
	{
		vuint32_t reserved:13;
		vuint32_t pin13:1;
	}Pins;

}R_ODR_t;

volatile R_ODR_t * P_ODR= &GPIO_PA_ODR;


int main(void)
{
	vuint32_t i;
	RCC_APB2ENR|=1<<2;
	GPIO_PA_CRH &= 0xff0fffff;
	GPIO_PA_CRH |= 0x00200000;

	while(1)
	{
		P_ODR->Pins.pin13=1;
		for(i=0;i<50000;i++);
		P_ODR->Pins.pin13=0;
		for(i=0;i<50000;i++);
	}
}
